# Generated by Django 5.0.3 on 2024-06-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('muscle_group', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('join_date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Sets',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_workout_id', models.CharField(max_length=10)),
                ('reps', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Workouts',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('workout_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('done_date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_id', models.CharField(max_length=10)),
                ('exercise_name', models.CharField(max_length=30)),
                ('reps', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
            ],
        ),
    ]
