version: "3.9"

services:
  workout:
    container_name: workoutapp
    build: .
    ports:
      - "8080:8080"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
    networks:
      - work-network
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - work-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
networks:
  work-network:
    name: work-network
    driver: bridge