# Generated by Django 5.0.6 on 2024-06-19 01:44

from django.db import migrations, models, connection

def check_and_drop_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'user_role_permissions') THEN
                    DROP TABLE public.user_role_permissions;
                END IF;
            END $$;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_assign_permissions'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(check_and_drop_table),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', to='auth.Permission', verbose_name='Permissions for this Role'),
        ),
    ]
