# Generated by Django 5.0.6 on 2024-06-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise', models.CharField(max_length=100)),
                ('reps', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done_date', models.TimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Sets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reps', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.sets')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.user_workouts')),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_workouts',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouts'),
        ),
        migrations.AddField(
            model_name='sets',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouts'),
        ),
    ]
