# Generated by Django 5.0.6 on 2024-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_sets',
            options={'permissions': [('can_view_user_sets', 'Can view User Sets'), ('can_edit_user_sets', 'Can edit User Sets'), ('can_delete_user_sets', 'Can delete User Sets')]},
        ),
        migrations.AlterModelOptions(
            name='user_workouts',
            options={'permissions': [('can_view_user_workouts', 'Can view User Workouts'), ('can_edit_user_workouts', 'Can edit User Workouts'), ('can_delete_user_workouts', 'Can delete User Workouts')]},
        ),
        migrations.AlterField(
            model_name='sets',
            name='exercise',
            field=models.CharField(max_length=100),
        ),
    ]
